//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthentifiedAccess.ServiceWeather {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWeather.IAccess")]
    public interface IAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/Weather", ReplyAction="http://tempuri.org/IAccess/WeatherResponse")]
        string Weather(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/Weather", ReplyAction="http://tempuri.org/IAccess/WeatherResponse")]
        System.Threading.Tasks.Task<string> WeatherAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessChannel : AuthentifiedAccess.ServiceWeather.IAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessClient : System.ServiceModel.ClientBase<AuthentifiedAccess.ServiceWeather.IAccess>, AuthentifiedAccess.ServiceWeather.IAccess {
        
        public AccessClient() {
        }
        
        public AccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Weather(string city) {
            return base.Channel.Weather(city);
        }
        
        public System.Threading.Tasks.Task<string> WeatherAsync(string city) {
            return base.Channel.WeatherAsync(city);
        }
    }
}
